/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { RaceFactory__factory } from "./RaceFactory__factory";
export { RaceInstance__factory } from "./RaceInstance__factory";
